# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
  - pip install music21

addons:
  apt:
    packages:
      - lilypond
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal

language: R
sudo: false
cache: packages
